# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sanctify < Formula
  desc "Automated semantic versioning and release tool"
  homepage "https://github.com/DrakeMazzy/sanctify"
  version "0.1.5"
  license "CC0-1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v0.1.5/sanctify_darwin_x86_64.tar.gz"
      sha256 "08453aa8c50ab40f3ed6598e075f89e321f267234af0638051ad20c1a4b49252"

      define_method(:install) do
        bin.install "sanctify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v0.1.5/sanctify_darwin_arm64.tar.gz"
      sha256 "d23c10a5b67d7b4cc8655e6a8ebbb5677d928835b15fdb564414937125d66499"

      define_method(:install) do
        bin.install "sanctify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v0.1.5/sanctify_linux_x86_64.tar.gz"
      sha256 "d48dc43b6464f846afe353339b06968573afaa1222937742a6b1cf2d53dab9ca"
      define_method(:install) do
        bin.install "sanctify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v0.1.5/sanctify_linux_arm64.tar.gz"
      sha256 "cbd02a8fe122c568720bd87678ad0e3868d835708c2945f387b8829725a1dc86"
      define_method(:install) do
        bin.install "sanctify"
      end
    end
  end

  test do
    system bin/"sanctify", "--version"
  end
end
