# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sanctify < Formula
  desc "Automated semantic versioning and release tool"
  homepage "https://github.com/DrakeMazzy/sanctify"
  version "0.1.4"
  license "CC0-1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v0.1.4/sanctify_darwin_x86_64.tar.gz"
      sha256 "c4d486bfb8815d756b64f46c57d0d0f79cf844ec3c9d0cb3720f5d12cd2c6b09"

      define_method(:install) do
        bin.install "sanctify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v0.1.4/sanctify_darwin_arm64.tar.gz"
      sha256 "e8a41e166dfe97602765d004fbb2793996687edd4e32ef62f64b4885dbe1ac06"

      define_method(:install) do
        bin.install "sanctify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v0.1.4/sanctify_linux_x86_64.tar.gz"
      sha256 "9c8830a59c440bc54c4ca43a7f70d91d32384e5b782299276e9ab6a843d05261"
      define_method(:install) do
        bin.install "sanctify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v0.1.4/sanctify_linux_arm64.tar.gz"
      sha256 "79554bdfe0965b784094859098a3619030c1f92f1dc9c00319af15055a9f3a73"
      define_method(:install) do
        bin.install "sanctify"
      end
    end
  end

  test do
    system bin/"sanctify", "--version"
  end
end
