# This file was generated by GoReleaser. DO NOT EDIT.
cask "sanctify" do
  version "0.1.8"

  on_macos do
    on_intel do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_darwin_x86_64.tar.gz"
      sha256 "19aca0fb917c645d8333f85c3385fb5e35b8044ab5fab66a755148479cdf12e7"
    end
    on_arm do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_darwin_arm64.tar.gz"
      sha256 "2ee540be1baecbaae47cfb130bb7f983df5bbb872973312adab878b283d397ba"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_linux_x86_64.tar.gz"
      sha256 "f1a0df98b634e4281759795a83c172528436f92b560768cdc859061ad0d8aa08"
    end
    on_arm do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_linux_arm64.tar.gz"
      sha256 "444e1624e626a73749974707adfc8d4e0aca86969e7738069a4a2c8946de76ab"
    end
  end

  name "sanctify"
  desc "Automated semantic versioning and release tool"
  homepage "https://github.com/DrakeMazzy/sanctify"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sanctify"

  # No zap stanza required

end
