# This file was generated by GoReleaser. DO NOT EDIT.
cask "sanctify" do
  version "0.1.9"

  on_macos do
    on_intel do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_darwin_x86_64.tar.gz"
      sha256 "4ecb67afb096105e92df3367183451be4045e564304376a96fd71616a512ae31"
    end
    on_arm do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_darwin_arm64.tar.gz"
      sha256 "887c243701a4d33357fa1c16c722ca9483c810f4b2bda1af0b082cef5453f3d4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_linux_x86_64.tar.gz"
      sha256 "61cd0b4f879486ccabbb25ced3177a420dac825a567513a97c743884b27894dd"
    end
    on_arm do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_linux_arm64.tar.gz"
      sha256 "32880c96d2c7d4d3c0d64a91784c48a884c5160fb1c1e135a91980bf09722d89"
    end
  end

  name "sanctify"
  desc "Automated semantic versioning and release tool"
  homepage "https://github.com/DrakeMazzy/sanctify"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sanctify"

  # No zap stanza required

  caveats <<~EOS
    On macOS, if the binary is blocked by Gatekeeper, run:
      xattr -d com.apple.quarantine $(brew --prefix)/bin/sanctify
  EOS
end
