# This file was generated by GoReleaser. DO NOT EDIT.
cask "sanctify" do
  version "0.1.8"

  on_macos do
    on_intel do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_darwin_x86_64.tar.gz"
      sha256 "680308c8b0e87a21a8eb84a4087ef077676a5514d1b4a9c74d92a9b29a1dabfb"
    end
    on_arm do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_darwin_arm64.tar.gz"
      sha256 "f0865ae5ff9daa73da974f29ac4dae6819a1ec9eff10ab5e57532e9ae7423989"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_linux_x86_64.tar.gz"
      sha256 "f4e3c536c9f8020f8a5da9824c499e9f7a8b349bcb411f83c7bcb153d54525b4"
    end
    on_arm do
      url "https://github.com/DrakeMazzy/sanctify/releases/download/v#{version}/sanctify_linux_arm64.tar.gz"
      sha256 "d92da7f95caa1832469764fbb688014ca0d11b1d2804357408df780bd2c1863c"
    end
  end

  name "sanctify"
  desc "Automated semantic versioning and release tool"
  homepage "https://github.com/DrakeMazzy/sanctify"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sanctify"

  # No zap stanza required

end
